### ISSUE TITLE
No CheckPhone PreDefault Event

### ISSUE THREAD

**Issue by gfgbsimao** [overextended/esx-npwd#3]
It would be nice to have an pre created event do check phone as an item, qb-npwd already have this, and i think it would be nice to have here to

**Comment by thelindat** [comment]
There’s builtin phone checks already.

scratch that I never pushed it 😭

**Comment by gfgbsimao** [comment]
So will it be pushed?

**Comment by thelindat** [comment]
> So will it be pushed?

https://github.com/overextended/esx-npwd/commit/bb5c21d3f7988adb002f9297711295587af2f708

Give that a go. Should work last I remember.

**Comment by gfgbsimao** [comment]
"PhoneAsItem": {
    "enabled": true,
    "exportResource": "my-core-resource",
    "exportFunction": "myCheckerFunction"
  },
  
what should i put here?

**Comment by thelindat** [comment]
I've set up the item handling differently, you don't need an export (set to false).
