### ISSUE TITLE
F1 - Not checking onPlayerLoaded item

### ISSUE THREAD

**Issue by Gameadictive** [overextended/esx-npwd#4]
![Captura](https://user-images.githubusercontent.com/65845786/170099092-52a6e708-3c40-4807-94a9-9582205bd2dc.PNG)
![Captura1](https://user-images.githubusercontent.com/65845786/170099085-72d699c1-e8a1-4150-941d-ca36455adf10.PNG)
![Captura2](https://user-images.githubusercontent.com/65845786/170099089-20e64303-2496-4203-97e6-bbce4eced868.PNG)

Any idea why this happening?

**Comment by thelindat** [comment]
Seems to be a race condition; somehow ESX hasn’t set its PlayerData yet.

Try adding a wait to the event.

**Comment by Gameadictive** [comment]
RegisterNetEvent('esx:playerLoaded', function()
       Citizen.Wait(500)   <---- Like this?
	if ESX.SearchInventory('phone') > 0 then
		npwd:setPhoneDisabled(false)
	end
end)
